"""export_fortran.py -- generate the Fortran side's data files from the banked
constants. Two outputs into fortran/data/:
  derived.dat        key-value lines: every derived constant the element laws need
                     (from derived-constants.json -- regenerated, never hand-edited)
  elem-reference.dat python's elem() per element: the U1 gate's expected values
Run from anywhere; paths derive from __file__."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gxtb_engine as GE  # noqa: E402

OUT = os.path.join(HERE, "..", "fortran", "data")
os.makedirs(OUT, exist_ok=True)

DC = json.load(open(os.path.join(HERE, "data", "derived-constants.json")))
with open(os.path.join(OUT, "derived.dat"), "w") as f:
    f.write("# generated by export_fortran.py -- do not edit\n")
    f.write("srule_p2_a  0.08247\n")
    f.write("srule_p2_b  0.0920\n")
    f.write("srule_h     0.4726\n")
    f.write("srule_he    0.9218\n")
    f.write("kb_scale    0.4223\n")
    f.write("cx_denom    9.59\n")
    for z, g in sorted(DC["es3"]["gamma"].items(), key=lambda t: int(t[0])):
        f.write(f"es3_gamma_{z}  {g}\n")
    f.write(f"es3_k3gs    {DC['es3']['k3gs']}\n")
    f.write(f"es3_k3gp    {DC['es3']['k3gp']}\n")

ZS = (1, 2, 6, 7, 8, 9)
with open(os.path.join(OUT, "elem-reference.dat"), "w") as f:
    f.write("# z nsh cx kb kd_sg kd_pi | per shell: k L2 MU U L5\n")
    for z in ZS:
        e = GE.elem(z)
        f.write(f"{z} {e['nsh']} {e['cx']:.14e} {e['kb']:.14e} "
                f"{e['kd_sg']:.14e} {e['kd_pi']:.14e}\n")
        for l in range(e["nsh"]):
            f.write(f"  {e['k'][l]:.14e} {e['L2'][l]:.14e} {e['MU'][l]:.14e} "
                    f"{e['U'][l]:.14e} {e['L5'][l]:.14e}\n")
print(f"exported derived.dat + elem-reference.dat for z = {ZS}")
